version: 2

models:
  - name: fct_shipments
    description: Shipment performance with carrier metrics and on-time delivery
    config:
      meta:
        kpis:
          - kpiName: 'On-Time Delivery Rate'
            acronym: 'On-Time %'
            description: 'Percentage of shipments delivered on time or early'
            calculation: 'sum(on_time_delivery_count) / count(shipment_id) * 100'
            sourceFieldName: 'is_on_time'
            granularity: 'Shipment'
            uniqueKey: 'shipment_id'
            dataType: 'percentage'
            department: 'Operations'
            dataOwner: ''
            businessOwner: ''
            note: 'Key carrier performance metric - wishlist section 6.2'

          - kpiName: 'Late Delivery Rate'
            acronym: 'Late %'
            description: 'Percentage of shipments delivered late'
            calculation: 'sum(late_delivery_count) / count(shipment_id) * 100'
            sourceFieldName: 'late_delivery_count'
            granularity: 'Shipment'
            uniqueKey: 'shipment_id'
            dataType: 'percentage'
            department: 'Operations'
            dataOwner: ''
            businessOwner: ''
            note: 'Delivery performance tracking'

          - kpiName: 'Shipping Cost per Order'
            acronym: ''
            description: 'Average shipping cost per order'
            calculation: 'sum(shipping_cost) / count(shipment_id)'
            sourceFieldName: 'shipping_cost'
            granularity: 'Shipment'
            uniqueKey: 'shipment_id'
            dataType: 'currency'
            department: 'Operations'
            dataOwner: ''
            businessOwner: ''
            note: 'Cost efficiency - wishlist section 6.2'

          - kpiName: 'Actual Transit Days'
            acronym: ''
            description: 'Number of days from pickup to delivery'
            calculation: 'date_diff(delivery_date, pickup_date, day)'
            sourceFieldName: 'actual_transit_days'
            granularity: 'Shipment'
            uniqueKey: 'shipment_id'
            dataType: 'duration'
            department: 'Operations'
            dataOwner: ''
            businessOwner: ''
            note: 'Delivery speed - wishlist section 6.3'

          - kpiName: 'Estimated Transit Days'
            acronym: ''
            description: 'Carrier estimated transit days'
            calculation: 'carrier_estimate'
            sourceFieldName: 'estimated_transit_days'
            granularity: 'Shipment'
            uniqueKey: 'shipment_id'
            dataType: 'duration'
            department: 'Operations'
            dataOwner: ''
            businessOwner: ''
            note: 'Carrier accuracy baseline'

          - kpiName: 'Delivery Issues by Region'
            acronym: ''
            description: 'Late deliveries grouped by destination state'
            calculation: 'sum(late_delivery_count) group by destination_state'
            sourceFieldName: 'destination_state'
            granularity: 'Shipment'
            uniqueKey: 'shipment_id'
            dataType: 'classification'
            department: 'Operations'
            dataOwner: ''
            businessOwner: ''
            note: 'Regional performance - wishlist section 6.2'

    columns:
      - name: shipment_id
        description: Unique shipment identifier
        tests:
          - unique
          - not_null

      - name: pickup_date
        description: Pickup date
        tests:
          - not_null

      - name: carrier
        description: Carrier name

      - name: shipping_cost
        description: Final shipping cost

      - name: estimated_transit_days
        description: Carrier's estimated transit days

      - name: actual_transit_days
        description: Actual transit days

      - name: is_on_time
        description: Boolean flag for on-time delivery

      - name: on_time_delivery_count
        description: Count flag for on-time deliveries (1 if on-time, 0 if late)

      - name: late_delivery_count
        description: Count flag for late deliveries

      - name: origin_state
        description: Origin state

      - name: destination_state
        description: Destination state
